[build-system]
    build-backend = "setuptools.build_meta"
    requires      = ["setuptools-scm>=8.0", "setuptools>=64"]

[project]
    authors = [
        { name = "Espressif Systems" },
    ]
    classifiers = ["Programming Language :: Python :: 3"]
    description = "ESP GPIO Tool"
    dynamic = ["version"]
    license = { file = "LICENSE" }
    name = "esp-gpio-tool"
    readme = "README.md"
    requires-python = ">=3.10"

    dependencies = [
        "pyyaml",
        "rich-click",
    ]


    [project.optional-dependencies]
        dev = [
            "czespressif",
            "pandas[excel]~=2.2.2",
        ]
        test = ["pytest-cov~=4.1.0", "pytest~=7.4.0"]

    [project.scripts]
        espins-cli = "esp_gpio_tool_cli.__main__:main"
        espins = "esp_gpio_tool.__main__:main"


[tool.codespell]
    skip = 'tests/*'
    ignore-words-list = ['emac']

[tool.ruff]
    line-length    = 120
    lint.select    = ['E', 'F', 'W', 'UP', 'I']
    target-version = "py310"

    [tool.ruff.format]
        quote-style = "single"
    [tool.ruff.lint.isort]
        force-single-line = true

[tool.mypy]
    disallow_incomplete_defs = false                               # Disallows defining functions with incomplete type annotations
    disallow_untyped_defs    = true                                # Disallows defining functions without type annotations or with incomplete type annotations
    exclude                  = '^venv/'                            # Paths to ignore during type checking
    ignore_missing_imports   = true                                # Suppress error messages about imports that cannot be resolved
    python_version           = "3.10"                              # Specifies the Python version used to parse and check the target program
    warn_no_return           = true                                # Shows errors for missing return statements on some execution paths
    warn_return_any          = true                                # Shows a warning when returning a value with type Any from a function declared with a non- Any return type
    no_implicit_optional     = false

[tool.commitizen]
    version                    = "0.1.0"
    name = "czespressif"
    major_version_zero         = true
    update_changelog_on_bump   = true
    tag_format                 = "v$version"
    changelog_start_rev        = "v0.1.0"
    annotated_tag              = true
    changelog_merge_prerelease = true
    bump_message               = "change: Updated release version to v$new_version"
    version_files              = [
        "esp_gpio_tool_cli/__init__.py:__version__"
    ]


[tool.setuptools.dynamic]
version = {attr = "esp_gpio_tool_cli.__version__"}

[tool.setuptools.packages]
find = {exclude = ["test", "test.*"]}

[tool.pytest.ini_options]
    addopts          = "-s --log-cli-level DEBUG --cov=esp_gpio_tool_cli --cov-report=term"
    python_classes   = ["Test*"]
    python_files     = ["test_*.py"]
    python_functions = ["test_*"]
    testpaths        = ["tests"]

[tool.coverage.run]
    omit = ["__*__.py", "*/tests/*", "esp_gpio_tool/*"]

[tool.yamlfix]
    line_length = 200
    whitelines = 1
    section_whitelines = 1
    sequence_style = "keep_style"
    explicit_start = false
